### ISSUE TITLE
Question: When the firmware kernel is not available, how to arbitrate.

### ISSUE THREAD

**Issue by newthis** [pr0v3rbs/FirmAE#3]
In most cases when the firmware kernel is not available,  how to extract the init processes information to improve firmadyne.

**Comment by 0xdkay** [comment]
To clarify, we did not extract the init program from the kernel, but extract the path of the init program.
In our paper, we used the kernel information for the images that have the kernel. 

Some firmware images may include the kernel, although the kernel cannot be nicely extracted. For those cases, you can still run the `strings` command and search for the "init=/" string after decompressing the image. Of course, not all kernel images have such paths because they can search the default path.

Meanwhile, I believe that most of firmware images share similar init paths. Therefore, you can collect the path strings in the firmware images that have the kernel, and then use the paths for the images that do not have the kernel.

Could you specify the cases or provide any more explanation?

**Comment by pr0v3rbs** [comment]
Especially, on the OpenWRT project based firmware need to init with `preinit` init program. [OpenWRT docs](https://openwrt.org/docs/techref/process.boot)
And the such init program information exist in the kernel command
(e.g., dlink DIR-550A_v1.10KRb09 - `root=/dev/mtdblock%d console=ttyS0,115200 init=/sbin/preinit`, netgear WNDR3800-V1.0.0.18 - `console=ttyS0,115200 root=31:09 rootfstype=squashfs init=/etc/preinit ...`)

However, the document indicate that use `/etc/preinit` program, some firmware images use `/sbin/preinit`.

You can extract the kernel data (Not complete one) by using [extractor.py](https://github.com/pr0v3rbs/FirmAE/blob/master/sources/extractor/extractor.py) without a `-nk` (no kernel) option.

If FirmAE cannot infer kernel command from the kernel data, then it finds the preinit file from extracted filesystem and try first-emulation with found init programs.
